Repository Basketball-Competition-Dashboard/Project, pull requests merged in 2024-06, with the labels that each got.

#8 Continue adjustment of PR #5 and sync with Web API Spec
  app/dataProcess_player_profiles.py
  app/routes.py
Labels: enhancement

#10 Add doc strings to declare stub functions
  app/routes.py
Labels: documentation

#15 Sync with Web API Spec (Auth)
  app/routes.py
Labels: enhancement

#16 Prevent SQL injection exploit
  app/dataProcess_player_profiles.py
  app/routes.py
Labels: security

#21 Change database paths, status codes, add a stub and remove two stubs
  app/dataProcess_games.py
  app/dataProcess_teams.py
  app/routes.py
Labels: bug

#22 Player-stats api typo
  app/dataProcess_teams.py
  app/routes.py
Labels: enhancement

#23 Player profile dev
  README.md
  app/dataProcess_player_profiles.py
  app/routes.py
Labels: enhancement

#24 CORS for Vite development server
  app/routes.py
  requirements.txt
Labels: enhancement

#27 Non-breaking Patch
  app/dataProcess_games.py
  app/dataProcess_player_profiles.py
  app/dataProcess_player_stats.py
  app/dataProcess_teams.py
  app/routes.py
Labels: bug

#29 Sync origin URL with API spec
  app/routes.py
  main.py
Labels: enhancement

#31 Fix Inconsistency between the Specification and Implementation
  app/dataProcess_player_profiles.py
  app/dataProcess_teams.py
  app/routes.py
Labels: bug
